### ISSUE TITLE
how can i execute?

### ISSUE THREAD

**Issue by wjcPure** [Doublelucker/NHOLS#1]
i use the commamd : julia> include("train.jl")
then occur a problem as follows:
julia> include("train.jl")
┌ Warning: `@pyimport foo` is deprecated in favor of `foo = pyimport("foo")`.
│   caller = _pywrap_pyimport(o::PyObject) at PyCall.jl:413
- Run `import Pkg; Pkg.add("ExcelFiles")` to install the ExcelFiles package.

Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:893
 [2] include(fname::String)
   @ Base.MainInclude .\client.jl:444
 [3] top-level scope
   @ F:\Postgraduate\Deeplearning\exercise\exe\Digraph\NHOLS-master\train.jl:3
 [4] include(fname::String)
   @ Base.MainInclude .\client.jl:444
 [5] top-level scope
   @ none:1
in expression starting at F:\Postgraduate\Deeplearning\exercise\exe\Digraph\NHOLS-master\src\tensors.jl:1
in expression starting at F:\Postgraduate\Deeplearning\exercise\exe\Digraph\NHOLS-master\train.jl:3

**Comment by Doublelucker** [comment]
Hello.

Well, as it's mentioned there, you have to install ExcelFiles first. If you use atom, you can just type ']' and then add ExcelFiles. Or run the suggested code in the julia console.

I'm sorry, that I didn't add the dependencies there, it was more of a test project.
